name: benchmark
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  bench:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v5
        with:
          cache: false
          go-version: '1.20'
      - uses: actions/checkout@v4
      - uses: n8maninger/action-golang-test@v2
        with:
          args: "-bench=.;-timeout=30m"

