name: revive
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/checkout@v3
      - uses: morphy2k/revive-action@v2
